-- Phase 3: durable background job infrastructure.
-- Safe by design: no existing endpoint, scheduler, or feature is rewired by
-- this migration. Workloads are migrated only after separate QA verification.

create table if not exists public.durable_jobs (
  id integer generated by default as identity primary key,
  user_id integer references public.auth_users(id) on delete cascade,
  job_type text not null,
  status text not null default 'QUEUED',
  idempotency_key text not null unique,
  payload_json text,
  result_json text,
  attempts integer not null default 0,
  max_attempts integer not null default 3,
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  finished_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint durable_jobs_status_check
    check (status in ('QUEUED','RUNNING','SUCCEEDED','FAILED')),
  constraint durable_jobs_attempts_check
    check (attempts >= 0),
  constraint durable_jobs_max_attempts_check
    check (max_attempts > 0)
);

create index if not exists durable_jobs_claim_idx
  on public.durable_jobs (status, available_at, id);

create index if not exists durable_jobs_user_idx
  on public.durable_jobs (user_id, created_at desc);

create index if not exists durable_jobs_type_status_idx
  on public.durable_jobs (job_type, status, created_at desc);

-- Only one active row is allowed for an idempotency key by the unique
-- constraint. This is the durable duplicate-submission guard.
