create table if not exists public.mutation_requests (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.auth_users(id) on delete cascade,
  operation text not null,
  idempotency_key text not null,
  response_json text,
  status text not null default 'RUNNING' check (status in ('RUNNING','SUCCEEDED')),
  locked_until timestamptz not null default (now() + interval '5 minutes'),
  created_at timestamptz not null default now(),
  unique(user_id, operation, idempotency_key)
);
create index if not exists idx_mutation_requests_user_created on public.mutation_requests(user_id, created_at desc);
