create table if not exists public.mutation_requests (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.auth_users(id) on delete cascade,
  operation text not null,
  idempotency_key text not null,
  response_json text not null,
  created_at timestamptz not null default now(),
  unique(user_id, operation, idempotency_key)
);
create index if not exists idx_mutation_requests_user_created on public.mutation_requests(user_id, created_at desc);
