-- Phase 3: durable workload queue.
-- Additive only. Existing tables, rows, indexes and Phase 2 cron jobs are untouched.

create table if not exists public.durable_jobs (
    id bigint generated by default as identity primary key,
    user_id bigint references public.auth_users(id) on delete cascade,
    job_type text not null,
    status text not null default 'QUEUED'
        check (status in ('QUEUED','RUNNING','SUCCEEDED','FAILED')),
    idempotency_key text not null unique,
    payload_json text,
    result_json text,
    attempts integer not null default 0 check (attempts >= 0),
    max_attempts integer not null default 3 check (max_attempts >= 1),
    available_at timestamptz not null default now(),
    locked_at timestamptz,
    finished_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists durable_jobs_claim_idx
    on public.durable_jobs (status, available_at, id);

create index if not exists durable_jobs_user_idx
    on public.durable_jobs (user_id, created_at desc);

create index if not exists durable_jobs_type_status_idx
    on public.durable_jobs (job_type, status, available_at);

-- Claiming is protected by the worker's transaction-level
-- FOR UPDATE SKIP LOCKED path. No trigger or cron is introduced here.
