CREATE TABLE IF NOT EXISTS public.durable_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type TEXT NOT NULL,
    profile_id BIGINT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    payload_json TEXT NOT NULL DEFAULT '{}',
    idempotency_key TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'QUEUED',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    locked_at TIMESTAMPTZ NULL,
    locked_by TEXT NULL,
    last_error TEXT NULL,
    result_json TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_durable_jobs_claim
    ON public.durable_jobs(status, available_at, created_at);

CREATE INDEX IF NOT EXISTS idx_durable_jobs_profile
    ON public.durable_jobs(profile_id, created_at);
